### ISSUE TITLE
Arbitrary attributes can be added to the configuration xml 

### ISSUE THREAD

**Issue by BeroSlingBlade** [Technolords/microservice-mock#13]
These attributes will not cause the validation of the config xml to fail.

**Comment by Technolords** [comment]
I am interested in the reproduction scenario, so add your files. When I try to add an attribute, I get this:

```
2016-10-13 16:18:16,965 [INFO] [main] [net.technolords.micro.config.ConfigurationManager] INFO  About to validate the configuration...
Exception in thread "main" org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 70; cvc-complex-type.3.2.2: Attribute 'attr' is not allowed to appear in element 'configuration'.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:452)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3230)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.processAttributes(XMLSchemaValidator.java:2707)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:2050)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:740)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:380)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2787)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
        at com.sun.org.apache.xerces.internal.jaxp.validation.StreamValidatorHelper.validate(StreamValidatorHelper.java:155)
        at com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorImpl.validate(ValidatorImpl.java:116)
        at javax.xml.validation.Validator.validate(Validator.java:124)
        at net.technolords.micro.config.ConfigurationManager.validateConfigurationFile(ConfigurationManager.java:168)
        at net.technolords.micro.config.ConfigurationManager.<init>(ConfigurationManager.java:72)
        at net.technolords.micro.MockedRestService.startService(MockedRestService.java:31)
        at net.technolords.micro.MockedRestService.main(MockedRestService.java:64)

```

**Comment by BeroSlingBlade** [comment]
I stand corrected. Retest does not show the initially reported incorrect behavior. Where was my mind?
